name: example
description: "Demonstration app for the flutter_pro_architect package."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  #media
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.2

  #app_config
  change_app_package_name: ^1.5.0

  #toast
  cherry_toast: ^1.13.0

  #core
  dartz: ^0.10.1

  #network
  dio: ^5.9.2
  dio_cache_interceptor: ^4.0.6
  equatable: ^2.0.8
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

  #env
  flutter_dotenv: ^6.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_pro_architect:
    path: ../

  #ui
  flutter_screenutil: ^5.9.3
  fluttertoast: ^9.0.0
  get_it: ^9.2.1

  #navigation
  go_router: ^17.2.3

  #icon
  hugeicons: ^1.1.7
  image_picker: ^1.2.2
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  rename_app: ^1.6.6
  retrofit: ^4.9.2
  synchronized: ^3.4.0
  talker_dio_logger: ^5.1.17
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

